using System.Diagnostics;
using System.Net.Sockets;
using System.Text;
using Agamemnon.Core.Util;
using Agamemnon.Platform.Windows;

namespace Agamemnon.Service;

/// <summary>
/// Runs ClamAV for the scanner: keeps clamd listening on 127.0.0.1:3310 and refreshes signatures
/// with freshclam every two hours. Hosted by the AgamemnonScanEngine service, which runs as
/// LocalService: clamd parses untrusted files, so it gets as few privileges as possible, and it
/// only ever sees file contents the scanning user streams to it.
/// </summary>
public sealed class ScanEngineHost(ILogger<ScanEngineHost> logger) : BackgroundService
{
    private static readonly TimeSpan UpdateInterval = TimeSpan.FromHours(2);

    private static string Clamd => Path.Combine(AgamemnonPaths.ClamAvBinaries, "clamd.exe");

    private static string Freshclam => Path.Combine(AgamemnonPaths.ClamAvBinaries, "freshclam.exe");

    private static string DataDir => AgamemnonPaths.ClamAvData;

    private static string DatabaseDir => Path.Combine(DataDir, "db");

    private static string ClamdConfig => Path.Combine(DataDir, "clamd.conf");

    private static string FreshclamConfig => Path.Combine(DataDir, "freshclam.conf");

    protected override async Task ExecuteAsync(CancellationToken stoppingToken)
    {
        if (!File.Exists(Clamd) || !File.Exists(Freshclam))
        {
            logger.LogError("ClamAV binaries not found in {Directory}", AgamemnonPaths.ClamAvBinaries);
            return;
        }

        WriteConfiguration();
        Task updates = UpdateLoopAsync(stoppingToken);

        // clamd can't start without signatures: wait for the first download.
        while (!HasDatabase() && !stoppingToken.IsCancellationRequested)
        {
            await Task.Delay(TimeSpan.FromSeconds(10), stoppingToken).ConfigureAwait(false);
        }

        TimeSpan backoff = TimeSpan.FromSeconds(5);
        while (!stoppingToken.IsCancellationRequested)
        {
            DateTimeOffset started = DateTimeOffset.UtcNow;
            int exitCode = await RunClamdAsync(stoppingToken).ConfigureAwait(false);
            if (stoppingToken.IsCancellationRequested)
            {
                break;
            }

            logger.LogWarning("clamd exited with code {ExitCode}; restarting in {Delay}", exitCode, backoff);
            await Task.Delay(backoff, stoppingToken).ConfigureAwait(false);
            backoff = DateTimeOffset.UtcNow - started > TimeSpan.FromMinutes(5)
                ? TimeSpan.FromSeconds(5)
                : TimeSpan.FromTicks(Math.Min(backoff.Ticks * 2, TimeSpan.FromMinutes(5).Ticks));
        }

        await updates.ConfigureAwait(false);
    }

    private static bool HasDatabase() =>
        Directory.Exists(DatabaseDir)
        && Directory.EnumerateFiles(DatabaseDir, "main.c?d").Any()
        && Directory.EnumerateFiles(DatabaseDir, "daily.c?d").Any();

    private static void WriteConfiguration()
    {
        Directory.CreateDirectory(DatabaseDir);
        File.WriteAllText(ClamdConfig, $"""
            # Generated by Agamemnon on every start. Edits are overwritten.
            TCPSocket 3310
            TCPAddr 127.0.0.1
            DatabaseDirectory {DatabaseDir}
            LogFile {Path.Combine(DataDir, "clamd.log")}
            LogFileMaxSize 5M
            LogRotate yes
            LogTime yes
            StreamMaxLength 512M
            MaxFileSize 512M
            MaxScanSize 1024M
            MaxThreads 4
            SelfCheck 3600
            ConcurrentDatabaseReload yes
            DetectPUA yes
            """, Encoding.ASCII);
        File.WriteAllText(FreshclamConfig, $"""
            # Generated by Agamemnon on every start. Edits are overwritten.
            DatabaseDirectory {DatabaseDir}
            UpdateLogFile {Path.Combine(DataDir, "freshclam.log")}
            LogFileMaxSize 2M
            LogTime yes
            DatabaseMirror database.clamav.net
            ConnectTimeout 30
            ReceiveTimeout 120
            """, Encoding.ASCII);
    }

    private async Task UpdateLoopAsync(CancellationToken stoppingToken)
    {
        while (!stoppingToken.IsCancellationRequested)
        {
            try
            {
                ProcessResult result = await ProcessRunner.Instance.RunAsync(
                    Freshclam,
                    [$"--config-file={FreshclamConfig}", "--stdout", "--no-warnings"],
                    TimeSpan.FromMinutes(20),
                    stoppingToken).ConfigureAwait(false);
                if (result.ExitCode == 0)
                {
                    logger.LogInformation("ClamAV signatures are up to date");
                    await ReloadClamdAsync(stoppingToken).ConfigureAwait(false);
                }
                else
                {
                    logger.LogWarning("freshclam failed ({ExitCode}): {Output}", result.ExitCode, result.StandardOutput.Trim());
                }
            }
            catch (Exception ex) when (ex is TimeoutException or IOException or System.ComponentModel.Win32Exception)
            {
                logger.LogWarning(ex, "Signature update failed");
            }

            try
            {
                // Retry sooner while there is no database at all.
                await Task.Delay(HasDatabase() ? UpdateInterval : TimeSpan.FromMinutes(2), stoppingToken).ConfigureAwait(false);
            }
            catch (OperationCanceledException)
            {
                return;
            }
        }
    }

    private static async Task ReloadClamdAsync(CancellationToken cancellationToken)
    {
        try
        {
            using var client = new TcpClient();
            await client.ConnectAsync("127.0.0.1", 3310, cancellationToken).ConfigureAwait(false);
            await client.GetStream().WriteAsync("zRELOAD\0"u8.ToArray(), cancellationToken).ConfigureAwait(false);
        }
        catch (SocketException)
        {
            // clamd not running yet; it loads the new signatures when it starts.
        }
    }

    private async Task<int> RunClamdAsync(CancellationToken stoppingToken)
    {
        var info = new ProcessStartInfo(Clamd)
        {
            UseShellExecute = false,
            CreateNoWindow = true,
            RedirectStandardOutput = true,
            RedirectStandardError = true,
        };
        info.ArgumentList.Add($"--config-file={ClamdConfig}");
        info.ArgumentList.Add("--foreground");

        using var process = new Process { StartInfo = info };
        process.OutputDataReceived += (_, e) => LogLine(e.Data);
        process.ErrorDataReceived += (_, e) => LogLine(e.Data);
        process.Start();
        process.BeginOutputReadLine();
        process.BeginErrorReadLine();
        try
        {
            await process.WaitForExitAsync(stoppingToken).ConfigureAwait(false);
            return process.ExitCode;
        }
        catch (OperationCanceledException)
        {
            process.Kill(entireProcessTree: true);
            return -1;
        }
    }

    private void LogLine(string? line)
    {
        if (!string.IsNullOrWhiteSpace(line))
        {
            logger.LogDebug("clamd: {Line}", line);
        }
    }
}
